name: "localfly"
services:
  localfly:
    container_name: localfly
    build: .
    ports:
      - "8080:3000"
    volumes:
      - ./localfly.db:/usr/src/app/localfly.db
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - NODE_ENV=production
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
        - action: rebuild
          path: ./package.json
