// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32
	Name         string
	PasswordHash string
	Onboarded    *bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserSession struct {
	ID                    int32
	UserID                int32
	AccessToken           string
	RefreshToken          string
	ExpiresAt             pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}
