// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
insert into user_sessions (
    user_id,
    access_token,
    refresh_token,
    expires_at,
    refresh_token_expires_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5
)
returning id, user_id, access_token, refresh_token, expires_at, refresh_token_expires_at, created_at
`

type CreateUserSessionParams struct {
	UserID                int32
	AccessToken           string
	RefreshToken          string
	ExpiresAt             pgtype.Timestamptz
	RefreshTokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshTokenExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSessionsByUserID = `-- name: DeleteUserSessionsByUserID :exec
delete from user_sessions
where user_id = $1
`

func (q *Queries) DeleteUserSessionsByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsByUserID, userID)
	return err
}

const getUserSessionByAccessToken = `-- name: GetUserSessionByAccessToken :one
select id, user_id, access_token, refresh_token, expires_at, refresh_token_expires_at, created_at
from user_sessions
where access_token = $1
`

func (q *Queries) GetUserSessionByAccessToken(ctx context.Context, accessToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByAccessToken, accessToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserSessionsByUserID = `-- name: ListUserSessionsByUserID :many
select id, user_id, access_token, refresh_token, expires_at, refresh_token_expires_at, created_at
from user_sessions
where user_id = $1
order by created_at desc
`

func (q *Queries) ListUserSessionsByUserID(ctx context.Context, userID int32) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listUserSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
