export enum ErrorCode {
    INTERNAL_ERROR = "INTERNAL_ERROR",

    INVALID_MESSAGE_FORMAT = "INVALID_MESSAGE_FORMAT",

    INVALID_ACCESS_TOKEN = "INVALID ACCESS_TOKEN",
    SESSION_EXPIRED = "SESSION_EXPIRED",
    AUTHENTICATION_TIMEOUT = "AUTHENTICATION_TIMEOUT",
    INVALID_RECONNECTION_TOKEN = "INVALID_RECONNECTION_TOKEN",
}

export enum WarningCode {
    MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN",
}
