// Code generated by go run ./cmd/protocolgen; DO NOT EDIT.
package protocol

import (
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/google/jsonschema-go/jsonschema"
)

type PacketID string

const (
	PacketIDClientHello            PacketID = "client.hello"
	PacketIDClientReady            PacketID = "client.ready"
	PacketIDServerError            PacketID = "server.error"
	PacketIDServerForceScene       PacketID = "server.force_scene"
	PacketIDServerKick             PacketID = "server.kick"
	PacketIDServerSetEnforcedState PacketID = "server.set_enforced_state"
	PacketIDServerWarning          PacketID = "server.warning"
	PacketIDServerWelcome          PacketID = "server.welcome"
)

type Envelope struct {
	ID   PacketID        `json:"id"`
	Data json.RawMessage `json:"data,omitempty"`
}

type ServerboundPacket interface {
	ID() PacketID
	isServerboundPacket()
}

type ClientboundPacket interface {
	ID() PacketID
	isClientboundPacket()
}

type ClientHello struct {
	AccessToken   string `json:"accessToken"`
	ClientVersion string `json:"clientVersion"`
	Device        string `json:"device"`
}

type ClientReady struct {
}

type ServerErrorCode string

const (
	ServerErrorCodeInternalError            ServerErrorCode = "INTERNAL_ERROR"
	ServerErrorCodeInvalidMessageFormat     ServerErrorCode = "INVALID_MESSAGE_FORMAT"
	ServerErrorCodeInvalidAccessToken       ServerErrorCode = "INVALID_ACCESS_TOKEN"
	ServerErrorCodeSessionExpired           ServerErrorCode = "SESSION_EXPIRED"
	ServerErrorCodeAuthenticationTimeout    ServerErrorCode = "AUTHENTICATION_TIMEOUT"
	ServerErrorCodeInvalidReconnectionToken ServerErrorCode = "INVALID_RECONNECTION_TOKEN"
	ServerErrorCodeClientAlreadyReady       ServerErrorCode = "CLIENT_ALREADY_READY"
)

type ServerError struct {
	Code    ServerErrorCode `json:"code"`
	Fatal   *bool           `json:"fatal,omitempty"`
	Message *string         `json:"message,omitempty"`
}

type ServerForceSceneScene string

const (
	ServerForceSceneSceneIntro ServerForceSceneScene = "INTRO"
)

type ServerForceScene struct {
	Scene ServerForceSceneScene `json:"scene"`
}

type ServerKickReason string

const (
	ServerKickReasonSessionInvalidated ServerKickReason = "SESSION_INVALIDATED"
)

type ServerKick struct {
	Reason ServerKickReason `json:"reason"`
}

type ServerSetEnforcedStateName string

const (
	ServerSetEnforcedStateNameCanHome ServerSetEnforcedStateName = "CAN_HOME"
)

type ServerSetEnforcedState struct {
	Name  ServerSetEnforcedStateName `json:"name"`
	Value bool                       `json:"value"`
}

type ServerWarningCode string

const (
	ServerWarningCodeMissingAccessToken ServerWarningCode = "MISSING_ACCESS_TOKEN"
)

type ServerWarning struct {
	Code    ServerWarningCode `json:"code"`
	Message string            `json:"message"`
}

type ServerWelcomeEnvironment string

const (
	ServerWelcomeEnvironmentDevelopment ServerWelcomeEnvironment = "development"
	ServerWelcomeEnvironmentProduction  ServerWelcomeEnvironment = "production"
)

type ServerWelcomeFeatureFlagsItem string

const (
	ServerWelcomeFeatureFlagsItemEnableExperimentalFeatures ServerWelcomeFeatureFlagsItem = "enableExperimentalFeatures"
	ServerWelcomeFeatureFlagsItemEnableDebugMode            ServerWelcomeFeatureFlagsItem = "enableDebugMode"
)

type ServerWelcome struct {
	ConnectionId  string                          `json:"connectionId"`
	Environment   ServerWelcomeEnvironment        `json:"environment"`
	FeatureFlags  []ServerWelcomeFeatureFlagsItem `json:"featureFlags"`
	ServerVersion string                          `json:"serverVersion"`
}

type ClientHelloPacket struct {
	Data ClientHello `json:"data"`
}

func (ClientHelloPacket) ID() PacketID         { return PacketIDClientHello }
func (ClientHelloPacket) isServerboundPacket() {}

type ClientReadyPacket struct {
	Data ClientReady `json:"data"`
}

func (ClientReadyPacket) ID() PacketID         { return PacketIDClientReady }
func (ClientReadyPacket) isServerboundPacket() {}

type ServerErrorPacket struct {
	Data ServerError `json:"data"`
}

func (ServerErrorPacket) ID() PacketID         { return PacketIDServerError }
func (ServerErrorPacket) isClientboundPacket() {}

type ServerForceScenePacket struct {
	Data ServerForceScene `json:"data"`
}

func (ServerForceScenePacket) ID() PacketID         { return PacketIDServerForceScene }
func (ServerForceScenePacket) isClientboundPacket() {}

type ServerKickPacket struct {
	Data ServerKick `json:"data"`
}

func (ServerKickPacket) ID() PacketID         { return PacketIDServerKick }
func (ServerKickPacket) isClientboundPacket() {}

type ServerSetEnforcedStatePacket struct {
	Data ServerSetEnforcedState `json:"data"`
}

func (ServerSetEnforcedStatePacket) ID() PacketID         { return PacketIDServerSetEnforcedState }
func (ServerSetEnforcedStatePacket) isClientboundPacket() {}

type ServerWarningPacket struct {
	Data ServerWarning `json:"data"`
}

func (ServerWarningPacket) ID() PacketID         { return PacketIDServerWarning }
func (ServerWarningPacket) isClientboundPacket() {}

type ServerWelcomePacket struct {
	Data ServerWelcome `json:"data"`
}

func (ServerWelcomePacket) ID() PacketID         { return PacketIDServerWelcome }
func (ServerWelcomePacket) isClientboundPacket() {}

var packetSchemas = map[PacketID]*jsonschema.Resolved{}

var generatedSchemaSources = map[string]string{
	"schemas/client.hello.schema.json":              "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"client.hello.schema.json\",\"title\":\"ClientHello\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"accessToken\",\"clientVersion\",\"device\"],\"properties\":{\"accessToken\":{\"type\":\"string\",\"minLength\":32,\"maxLength\":32},\"clientVersion\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":64},\"device\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":256}}}",
	"client.hello.schema.json":                      "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"client.hello.schema.json\",\"title\":\"ClientHello\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"accessToken\",\"clientVersion\",\"device\"],\"properties\":{\"accessToken\":{\"type\":\"string\",\"minLength\":32,\"maxLength\":32},\"clientVersion\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":64},\"device\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":256}}}",
	"schemas/client.ready.schema.json":              "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"client.ready.schema.json\",\"title\":\"ClientReady\",\"type\":\"object\",\"additionalProperties\":false,\"properties\":{}}",
	"client.ready.schema.json":                      "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"client.ready.schema.json\",\"title\":\"ClientReady\",\"type\":\"object\",\"additionalProperties\":false,\"properties\":{}}",
	"schemas/server.error.schema.json":              "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.error.schema.json\",\"title\":\"ServerError\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"code\"],\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\",\"enum\":[\"INTERNAL_ERROR\",\"INVALID_MESSAGE_FORMAT\",\"INVALID_ACCESS_TOKEN\",\"SESSION_EXPIRED\",\"AUTHENTICATION_TIMEOUT\",\"INVALID_RECONNECTION_TOKEN\",\"CLIENT_ALREADY_READY\"]},\"fatal\":{\"type\":\"boolean\"}}}",
	"server.error.schema.json":                      "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.error.schema.json\",\"title\":\"ServerError\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"code\"],\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\",\"enum\":[\"INTERNAL_ERROR\",\"INVALID_MESSAGE_FORMAT\",\"INVALID_ACCESS_TOKEN\",\"SESSION_EXPIRED\",\"AUTHENTICATION_TIMEOUT\",\"INVALID_RECONNECTION_TOKEN\",\"CLIENT_ALREADY_READY\"]},\"fatal\":{\"type\":\"boolean\"}}}",
	"schemas/server.force_scene.schema.json":        "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.force_scene.schema.json\",\"title\":\"ServerForceScene\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"scene\"],\"properties\":{\"scene\":{\"type\":\"string\",\"enum\":[\"INTRO\"]}}}",
	"server.force_scene.schema.json":                "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.force_scene.schema.json\",\"title\":\"ServerForceScene\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"scene\"],\"properties\":{\"scene\":{\"type\":\"string\",\"enum\":[\"INTRO\"]}}}",
	"schemas/server.kick.schema.json":               "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.kick.schema.json\",\"title\":\"ServerKick\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"reason\"],\"properties\":{\"reason\":{\"type\":\"string\",\"enum\":[\"SESSION_INVALIDATED\"]}}}",
	"server.kick.schema.json":                       "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.kick.schema.json\",\"title\":\"ServerKick\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"reason\"],\"properties\":{\"reason\":{\"type\":\"string\",\"enum\":[\"SESSION_INVALIDATED\"]}}}",
	"schemas/server.set_enforced_state.schema.json": "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.set_enforced_state.schema.json\",\"title\":\"ServerSetEnforcedState\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"name\",\"value\"],\"properties\":{\"name\":{\"type\":\"string\",\"enum\":[\"CAN_HOME\"]},\"value\":{\"type\":\"boolean\"}}}",
	"server.set_enforced_state.schema.json":         "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.set_enforced_state.schema.json\",\"title\":\"ServerSetEnforcedState\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"name\",\"value\"],\"properties\":{\"name\":{\"type\":\"string\",\"enum\":[\"CAN_HOME\"]},\"value\":{\"type\":\"boolean\"}}}",
	"schemas/server.warning.schema.json":            "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.warning.schema.json\",\"title\":\"ServerWarning\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"message\",\"code\"],\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\",\"enum\":[\"MISSING_ACCESS_TOKEN\"]}}}",
	"server.warning.schema.json":                    "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.warning.schema.json\",\"title\":\"ServerWarning\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"message\",\"code\"],\"properties\":{\"message\":{\"type\":\"string\"},\"code\":{\"type\":\"string\",\"enum\":[\"MISSING_ACCESS_TOKEN\"]}}}",
	"schemas/server.welcome.schema.json":            "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.welcome.schema.json\",\"title\":\"ServerWelcome\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"connectionId\",\"serverVersion\",\"environment\",\"featureFlags\"],\"properties\":{\"connectionId\":{\"type\":\"string\",\"minLength\":1},\"serverVersion\":{\"type\":\"string\",\"minLength\":1},\"environment\":{\"type\":\"string\",\"enum\":[\"development\",\"production\"]},\"featureFlags\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"enableExperimentalFeatures\",\"enableDebugMode\"]}}}}",
	"server.welcome.schema.json":                    "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"server.welcome.schema.json\",\"title\":\"ServerWelcome\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"connectionId\",\"serverVersion\",\"environment\",\"featureFlags\"],\"properties\":{\"connectionId\":{\"type\":\"string\",\"minLength\":1},\"serverVersion\":{\"type\":\"string\",\"minLength\":1},\"environment\":{\"type\":\"string\",\"enum\":[\"development\",\"production\"]},\"featureFlags\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"enum\":[\"enableExperimentalFeatures\",\"enableDebugMode\"]}}}}",
}

func init() {
	mustRegisterPacketSchema(PacketIDClientHello, "schema://echoform/schemas/client.hello.schema.json", generatedSchemaSources["schemas/client.hello.schema.json"])
	mustRegisterPacketSchema(PacketIDClientReady, "schema://echoform/schemas/client.ready.schema.json", generatedSchemaSources["schemas/client.ready.schema.json"])
	mustRegisterPacketSchema(PacketIDServerError, "schema://echoform/schemas/server.error.schema.json", generatedSchemaSources["schemas/server.error.schema.json"])
	mustRegisterPacketSchema(PacketIDServerForceScene, "schema://echoform/schemas/server.force_scene.schema.json", generatedSchemaSources["schemas/server.force_scene.schema.json"])
	mustRegisterPacketSchema(PacketIDServerKick, "schema://echoform/schemas/server.kick.schema.json", generatedSchemaSources["schemas/server.kick.schema.json"])
	mustRegisterPacketSchema(PacketIDServerSetEnforcedState, "schema://echoform/schemas/server.set_enforced_state.schema.json", generatedSchemaSources["schemas/server.set_enforced_state.schema.json"])
	mustRegisterPacketSchema(PacketIDServerWarning, "schema://echoform/schemas/server.warning.schema.json", generatedSchemaSources["schemas/server.warning.schema.json"])
	mustRegisterPacketSchema(PacketIDServerWelcome, "schema://echoform/schemas/server.welcome.schema.json", generatedSchemaSources["schemas/server.welcome.schema.json"])
}

func mustRegisterPacketSchema(id PacketID, baseURI string, raw string) {
	var schema jsonschema.Schema
	if err := json.Unmarshal([]byte(raw), &schema); err != nil {
		panic(fmt.Sprintf("parse schema %s: %v", id, err))
	}
	resolved, err := schema.Resolve(&jsonschema.ResolveOptions{BaseURI: baseURI, Loader: generatedSchemaLoader})
	if err != nil {
		panic(fmt.Sprintf("resolve schema %s: %v", id, err))
	}
	packetSchemas[id] = resolved
}

func generatedSchemaLoader(uri *url.URL) (*jsonschema.Schema, error) {
	key := uri.Path
	if len(key) > 0 && key[0] == '/' {
		key = key[1:]
	}
	raw, ok := generatedSchemaSources[key]
	if !ok {
		raw, ok = generatedSchemaSources[uri.String()]
	}
	if !ok {
		return nil, fmt.Errorf("schema %q is not embedded", uri.String())
	}
	var schema jsonschema.Schema
	if err := json.Unmarshal([]byte(raw), &schema); err != nil {
		return nil, err
	}
	return &schema, nil
}

func ValidatePacketData(id PacketID, data json.RawMessage) error {
	schema, ok := packetSchemas[id]
	if !ok {
		return fmt.Errorf("unknown packet id %q", id)
	}
	if len(data) == 0 {
		data = json.RawMessage(`{}`)
	}
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return schema.Validate(value)
}

func DecodeServerbound(data []byte) (ServerboundPacket, error) {
	var envelope Envelope
	if err := json.Unmarshal(data, &envelope); err != nil {
		return nil, err
	}
	switch envelope.ID {
	case PacketIDClientHello:
		payload, err := decodePacketData[ClientHello](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ClientHelloPacket{Data: payload}, nil
	case PacketIDClientReady:
		payload, err := decodePacketData[ClientReady](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ClientReadyPacket{Data: payload}, nil
	default:
		return nil, fmt.Errorf("unknown serverbound packet id %q", envelope.ID)
	}
}

func DecodeClientbound(data []byte) (ClientboundPacket, error) {
	var envelope Envelope
	if err := json.Unmarshal(data, &envelope); err != nil {
		return nil, err
	}
	switch envelope.ID {
	case PacketIDServerError:
		payload, err := decodePacketData[ServerError](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerErrorPacket{Data: payload}, nil
	case PacketIDServerForceScene:
		payload, err := decodePacketData[ServerForceScene](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerForceScenePacket{Data: payload}, nil
	case PacketIDServerKick:
		payload, err := decodePacketData[ServerKick](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerKickPacket{Data: payload}, nil
	case PacketIDServerSetEnforcedState:
		payload, err := decodePacketData[ServerSetEnforcedState](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerSetEnforcedStatePacket{Data: payload}, nil
	case PacketIDServerWarning:
		payload, err := decodePacketData[ServerWarning](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerWarningPacket{Data: payload}, nil
	case PacketIDServerWelcome:
		payload, err := decodePacketData[ServerWelcome](envelope.ID, envelope.Data)
		if err != nil {
			return nil, err
		}
		return ServerWelcomePacket{Data: payload}, nil
	default:
		return nil, fmt.Errorf("unknown clientbound packet id %q", envelope.ID)
	}
}

func EncodeServerbound(packet ServerboundPacket) ([]byte, error) {
	switch p := packet.(type) {
	case ClientHelloPacket:
		return encodeEnvelope(PacketIDClientHello, p.Data)
	case *ClientHelloPacket:
		return encodeEnvelope(PacketIDClientHello, p.Data)
	case ClientReadyPacket:
		return encodeEnvelope(PacketIDClientReady, p.Data)
	case *ClientReadyPacket:
		return encodeEnvelope(PacketIDClientReady, p.Data)
	default:
		return nil, fmt.Errorf("unsupported serverbound packet type %T", packet)
	}
}

func EncodeClientbound(packet ClientboundPacket) ([]byte, error) {
	switch p := packet.(type) {
	case ServerErrorPacket:
		return encodeEnvelope(PacketIDServerError, p.Data)
	case *ServerErrorPacket:
		return encodeEnvelope(PacketIDServerError, p.Data)
	case ServerForceScenePacket:
		return encodeEnvelope(PacketIDServerForceScene, p.Data)
	case *ServerForceScenePacket:
		return encodeEnvelope(PacketIDServerForceScene, p.Data)
	case ServerKickPacket:
		return encodeEnvelope(PacketIDServerKick, p.Data)
	case *ServerKickPacket:
		return encodeEnvelope(PacketIDServerKick, p.Data)
	case ServerSetEnforcedStatePacket:
		return encodeEnvelope(PacketIDServerSetEnforcedState, p.Data)
	case *ServerSetEnforcedStatePacket:
		return encodeEnvelope(PacketIDServerSetEnforcedState, p.Data)
	case ServerWarningPacket:
		return encodeEnvelope(PacketIDServerWarning, p.Data)
	case *ServerWarningPacket:
		return encodeEnvelope(PacketIDServerWarning, p.Data)
	case ServerWelcomePacket:
		return encodeEnvelope(PacketIDServerWelcome, p.Data)
	case *ServerWelcomePacket:
		return encodeEnvelope(PacketIDServerWelcome, p.Data)
	default:
		return nil, fmt.Errorf("unsupported clientbound packet type %T", packet)
	}
}

func decodePacketData[T any](id PacketID, data json.RawMessage) (T, error) {
	var payload T
	if len(data) == 0 {
		data = json.RawMessage(`{}`)
	}
	if err := ValidatePacketData(id, data); err != nil {
		return payload, err
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		return payload, err
	}
	return payload, nil
}

func encodeEnvelope(id PacketID, payload any) ([]byte, error) {
	data, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	if err := ValidatePacketData(id, data); err != nil {
		return nil, err
	}
	return json.Marshal(Envelope{ID: id, Data: data})
}
